// <auto-generated />
namespace Security.DataLayer.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedkeysRoleMonitor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedkeysRoleMonitor));
        
        string IMigrationMetadata.Id
        {
            get { return "201809131444042_added keys RoleMonitor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
