// <auto-generated />
namespace Security.DataLayer.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedsomemorerepositories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsomemorerepositories));
        
        string IMigrationMetadata.Id
        {
            get { return "201808271300353_added some more repositories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
