// <auto-generated />
namespace Security.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class renamedRoomproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamedRoomproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201808201506380_renamed Room property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
